### ISSUE TITLE
Authentik is not returning back to netbird when adding peers

### ISSUE THREAD

**Issue by Akruidenberg** [netbirdio/netbird#1003]
I''m running a self hosting Netbird instance with Authentik as IDP backend. Traefik is running as reverse proxy with my own domain. I''m using Docker with the Traefik example file in this repo.
Ports in the self hosting guide are open in the Router. 

Both are running at the same machine. The web interface is running fine now. However, i have problems when adding peers. 
Log-in with Authentik is working fine. After that, Authentik is returning back to an URL like https://authentik.mydomain.com/device?code=XXXXXX with a white page. 
Because the web interface is working (adding DNS, routes etc.) i don't how to troubleshoot.
Running a docker container with a setup key will add the peer to the web interface, but it's not coming online. Also, the "last seen" field is not updated.

**To Reproduce**
1. Open a Netbird client like the android App
2. Change the Url to the correct server and log-in with Authentik
3. https://authentik.mydomain.com/device?code=XXXXXX) with a white page is shown.
4. The following error is shown in the Management container:
`### 2023-07-05T16:22:51+02:00 WARN management/server/grpcserver.go:322: failed logging in peer R7Z6hJvUc6+dCLF3Y3U7rpfreXIwhPEqygmEPFrpEXs=`

**Expected behavior**
A new page with Netbird must be shown to complete the steps.

**NetBird status -d output:**
If applicable, add the output of the `netbird status -d` command

Coming soon this afternoon!

**Screenshots**
Coming soon this Afternoon!

**Additional context**
Coming soon this afternoon!

I will upload the files needed like the compose file and logs this afternoon. I'm so close to getting Netbird running and I''m really excited  to fix this problem!

Thanks in advance so far.

**Comment by mlsmaycon** [comment]
@bcmmbaga This is similar to #1015.

@Akruidenberg can you share your authentik version for us to check the doc steps against it?

**Comment by bcmmbaga** [comment]
It seems that the issue you're experiencing is due to the lack of a default device auth flow configured in authentik. To resolve this, you can follow these steps:

- Go to the authentik admin interface
-On the left menu, click on `System` and then select `Tenants`
- If you haven't set a custom tenant, choose `authentik-default` and click the edit button
- Scroll down to` Default flows `and update the `Device code flow` to use the `default-authenticator-static-setup (default-authenticator-static-setup)` flow
- Click on `Update`, and then you can try the client login again with netbird.

Please let us know if this resolves the issue.

**Comment by Akruidenberg** [comment]
Sorry for my late reaction! Problem is fixed. Thank you for your support.
