### ISSUE TITLE
Configuration to permanently disable the experimental `Enable remote SSH access` feature.

### ISSUE THREAD

**Issue by dr-lux** [netbirdio/netbird#1868]
**Is your feature request related to a problem? Please describe.**
The experimental `Enable remote SSH Access` feature may allow a Netbird administrator to enable a peer's remote SSH access. This can lead to insecure enforcement of internal policies (such as lockdown of the SSH service or control through bastion access).

**Describe the solution you'd like**
Would it be possible to add a configuration argument to permanently disable this feature? This would prevent a Netbird administrator from enabling this feature. 

**Additional context**
I'm self-hosting Netbird.

Thanks!

**Comment by pascal-fischer** [comment]
Hi @dr-lux,
with version [0.26.0](https://github.com/netbirdio/netbird/releases/tag/v0.26.0) we changed the behavior of the ssh server and added a flag `--allow-server-ssh` to the client. This way the end user needs to explicitly allow ssh access to their device, otherwise even the administrator is unable to start the ssh server. Meaning now it requires both, the users consent and the enabled ssh server in the admin panel for anyone to connect to that peer via ssh.

**Comment by dr-lux** [comment]
Hi @pascal-fischer thanks a lot for the clarification. I think it was not well explain through the documentation.

**Comment by simonmicro** [comment]
@pascal-fischer I fear this change is not working anymore. I freshly set up `v0.28.7` on my machines and was able to activate the SSH access without any hurdles (after enabling it in the web interface).

This is really not good, as I do not want to have root-access to the machines of my other users!
