### ISSUE TITLE
Netbird dashboard not working

### ISSUE THREAD

**Issue by dertruffel** [netbirdio/netbird#2458]
**Describe the problem**

I installed netbird on Win10 and later upgraded to Win11 to try and fix it.
Netbird connects both with CLI and UI, but dashboard doesn't work.

**To Reproduce**

1. Install netbird and connect
2. Go tohttps://app.netbird.io/
3. Netbird not detected and asks to install it

**Expected behavior**

Have access to the dashboard

**Are you using NetBird Cloud?**

NetBird cloud used

**NetBird version**

0.28.8

**NetBird status -dA output:**
(peers not included for privacy)

OS: windows/amd64
Daemon version: 0.28.8
CLI version: 0.28.8
Management: Connected to https://api.netbird.io:443
Signal: Connected to https://signal.netbird.io:443
Relays:
  [stun:stun.netbird.io:5555] is Available
  [turns:turn.netbird.io:443?transport=tcp] is Available
Nameservers:
FQDN: desktop-yourmom.netbird.cloud
NetBird IP: 100.111.167.5/16
Interface type: Userspace
Quantum resistance: false
Routes: -
Peers count: 4/12 Connected

**Do you face any (non-mobile) client issues?**

[netbird.debug.4052076447.zip](https://github.com/user-attachments/files/16681970/netbird.debug.4052076447.zip)
1min -AS debug

**Screenshots**

![brave_OzbHVHofhU](https://github.com/user-attachments/assets/d40f8e7f-d764-4276-aafb-294dbcc86780)

**Additional context**

I tried installing on WSL2 and running in mirrored networking, host windows doesn't detect netbird and if i run firefox/brave i get the same issue as on Windows.
Adblockers and tracker blockers disabled, affects Edge as well as Brave, Firefox on WSL2 doesn't pick it up as well.

**Comment by bcmmbaga** [comment]
Hello @dertruffel , This issue is due to restricted permissions for regular users. Access to the dashboard is limited, meaning regular users will not be able to view any peers. 

To remove this restriction, you can log in with an admin account, or if you're not an admin, you can ask the admin to navigate to `Settings > Permissions` and disable the `Restrict dashboard for regular users` option

![Screenshot from 2024-08-21 12-18-24](https://github.com/user-attachments/assets/3216a07a-4fcd-47c7-b51a-17f27481ae17)

**Comment by dertruffel** [comment]
Thank you, works and lets me use the dashboard
