### ISSUE TITLE
Netbird can't query users when using newer versions than Zitadel 2.61.0

### ISSUE THREAD

**Issue by Kidswiss** [netbirdio/netbird#2616]
**Describe the problem**

When updating Zitadel to 2.61.2 or anything newer, then Netbird can't query the Zitadel user endpoint anymore.

**To Reproduce**

1. Install Netbird v0.29.3
2. Install Zitdadel 2.61.1 or newer
3. Get 403 during login

**Expected behavior**

Zitadel integration should still work if it gets updated.

**Are you using NetBird Cloud?**

Selfhosted

**NetBird version**

`0.29.3`

**Additional context**

Netbird management logs
```
2024-09-18T14:31:43Z WARN [context: SYSTEM] management/server/account.go:1017: failed warming up cache due to error: unable to post https://idp.secret.ch/management/v1/users/_search, statusCode 403
```

Zitadel log entries:
```	
time="2024-09-18T14:36:52Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:283" error="ID=APP-ASdgg Message=invalid token"
```

I've tried re-creating the service account secret, but the error persisted. Also, not sure if this is an issue on Zitadel's side or on Netbird. But given that Netbird is the only app I had issues with, I opened a bug here.

**Comment by landmass-deftly-reptile-budget** [comment]
Can confirm the same issue with Zitadel 2.62.1 and Netbird 0.29.3
Additional logs from netbird-management container:
ERRO [requestID: 098374cd-f244-4be6-91f4-9b3e02fb292f, context: HTTP] management/server/http/util/util.go:81: got a handler error: token invalid
ERRO [context: HTTP, requestID: 098374cd-f244-4be6-91f4-9b3e02fb292f] management/server/http/middleware/auth_middleware.go:89: Error when validating JWT claims: unable to post https://bla.blabla.com/management/v1/users/_search, statusCode 403

The logs in the Zitadel container are identical like above.

**Comment by bcmmbaga** [comment]
I see that Zitadel released [v2.62.1](https://github.com/zitadel/zitadel/releases/tag/v2.62.1) two days ago, but they have now marked [v2.59.3](https://github.com/zitadel/zitadel/releases/tag/v2.59.3) as the latest version. Could you try using v2.59.3 (latest) for now or  rollback to the previous version that was working for you? 

In meantime we will run tests to confirm the breaking changes and update the NetBird Zitadel implementation accordingly.

**Comment by landmass-deftly-reptile-budget** [comment]
> I see that Zitadel released [v2.62.1](https://github.com/zitadel/zitadel/releases/tag/v2.62.1) two days ago, but they have now marked [v2.59.3](https://github.com/zitadel/zitadel/releases/tag/v2.59.3) as the latest version. Could you try using v2.59.3 (latest) for now or rollback to the previous version that was working for you?
> 
> In meantime we will run tests to confirm the breaking changes and update the NetBird Zitadel implementation accordingly.

This is for sure some mistake by Zitadel tagging this version 2.59.3 as "latest".
See [https://github.com/zitadel/zitadel/releases](https://github.com/zitadel/zitadel/releases)
They have several versions updated in that last days with all these three bug fixes mentioned (from 2.54.x to 2.62.x).

**Comment by adasauce** [comment]
I just wanted to follow up with both a "me too" and some info from the zitadel side. the events history does say a token was created and authenticated properly for me. so it appears to be some kind of permission issue just with the netbird user accessing that endpoint.

I have some experience writing integrations with zitadel, I'll poke around to see what netbird is calling vs. what the api is expecting.

**Comment by adasauce** [comment]
another follow-up:

I added a PAT for the netbird user and made changes to the management service overloading the ClientSecret and Authenticate method to just make a pretend JWT with the AccessToken being the PAT to use that instead of authenticating a JWT and everything seems to be working fine this way since it just concatenates `Bearer + accessToken` to assemble it before a request is made.

I think it would be a relatively simple change to just use a PAT and refactor the config a bit if we want to swerve this issue. I'll keep tweaking configurations and hacking on both sides to see if I can find the real cause though.

In the meantime at least my management service is back online :)

**Comment by adasauce** [comment]
more extra data:

I added support in netbird for using the Bearer "Access Token Type" instead of JWT from zitadel as well, and get the same `could not read projectid by clientid` error as before. So it's not to do with receiving and passing the jwt access token.

I also tried adding the `urn:zitadel:iam:org:project:id:{projectid}:aud` scope to the scopes when making the access token request as noted here: https://zitadel.com/docs/guides/integrate/service-users/client-credentials#2-authenticating-a-service-user-and-request-a-token but that also didn't make a difference.

**Comment by adasauce** [comment]
I'm getting another chance to look at this today and at this point I'm pretty sure there's some undesired behaviour going on the zitadel side here. I've followed all of the specs A-Z to build this token for a service user from their docs and their examples, but none of them will authenticate. 

I think it may have been introduced in a big refactor on their side at `8e0c8393`. If I make a small change to the auth flow in zitadel and not assume any client_id request a project request, only checking clientid against projectid when it's of the <id>@<org> format and continuing on otherwise with the rest of the auth flow, everything works again. I'm going to open up an issue on the zitadel side and see if I can learn some more there.

**Comment by alexcupertme** [comment]
Can agree issue exists on Zitadel v2.62.1
Downgraded to v2.61.1 and all works perfectly, even after i rebooted Netbird and Zitadel, tried to catch this issue

**Comment by landmass-deftly-reptile-budget** [comment]
> Can agree issue exists on Zitadel v2.62.1 Downgraded to v2.61.1 and all works perfectly, even after i rebooted Netbird and Zitadel, tried to catch this issue

Thanks for the hint. Can confirm 2.61.1 gets the access to the dashboard working again.

**Comment by Kidswiss** [comment]
I've just tested against Zitadel's latest release, it's working now for me.

https://github.com/zitadel/zitadel/releases/tag/v2.62.4

**Comment by dlhck** [comment]
Getting this error right now with v2.64.1
