### ISSUE TITLE
UDP 49152-65535

### ISSUE THREAD

**Issue by chmis8000** [netbirdio/netbird#278]
UDP 49152-65535
Any suggestions on the configuration of the server and client?

**Comment by shatoboar** [comment]
Hey @chmis8000, thanks for taking the time to create the issue. Could you specify your problem a little bit more?

**Comment by chmis8000** [comment]
@shatoboar  
This documentation https://github.com/wiretrustee/wiretrustee/blob/main/docs/self-hosting.md mentions it.
"Coturn is used for relay using the STUN/TURN protocols. It requires a listening port, UDP 3478, and range of ports,UDP 49152-65535, for dynamic relay connections."

**Comment by chmis8000** [comment]
I think two clients cannot p2p, 
but one machine can be configured with port mapping. Is it possible to increase the configuration so as to try to p2p as much as possible?

**Comment by shatoboar** [comment]
Hi sorry for the delayed answer. 
I am not exactly sure what you mean, but peers continuously try to establish a peer-to-peer connection. You don't need to increase the configuration in order for this to happen. 
Why is it that you think that the two clients are unable to connect p2p?

**Comment by mlsmaycon** [comment]
Hello @chmis8000, you are correct, the peer with Symmetric NAT is causing this issue. 

we rely on [ICE protocol](https://datatracker.ietf.org/doc/html/rfc8445) for NAT discovery, it evaluates all types of connections and only uses the relay server in case no direct connection is possible. Also, you may be facing some performance issues due to the distance to our relay servers, currently, they are hosted in Finland, but we have an estimate to expand their deployment around the globe in May.
