### ISSUE TITLE
Management Service Read Timeout

### ISSUE THREAD

**Issue by diseq** [netbirdio/netbird#418]
i'm testing netbird behind nginx. Is there a recommended read timeout value for the management service?

per default, gprc proxy terminates after one minute leading to this:
```
time="2022-08-08T19:21:14+02:00" level=warning msg="disconnected from the Management service but will retry silently. Reason: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR"
```

i configured nginx now with this, though not sure if 1h is too much. are there regular management service checkins?
```
location /management.ManagementService {
  grpc_pass grpc://127.0.0.1:8081;
  grpc_read_timeout 60m;              
}
```

**Comment by braginini** [comment]
Hey @diseq 
There is no polling mechanism (check-ins). Instead, every NetBird agent keeps an open gRPC stream with the Management service. Once there is something to send (e.g., network map update) the Management service uses this stream to deliver updates to agnets. So there should be no timeout at all so that the stream is always open. However, agents will reconnect automatically and continue to operate normally.

**Comment by diseq** [comment]
thanks. well understood!
