### ISSUE TITLE
Self hosted keycloak integration shows user ID under email in netbird ui

### ISSUE THREAD

**Issue by finnje** [netbirdio/netbird#469]
For some reason keycloak users info is not being pulled properly when displayed in the netbird ui 

**Keycloak** UI

![Screen Shot 2022-09-13 at 9 16 49 AM](https://user-images.githubusercontent.com/4070974/189911278-15a81fb9-0af7-48b8-90a9-c94c57490c49.png)

**Netbird** UI

![Screen Shot 2022-09-13 at 9 12 10 AM](https://user-images.githubusercontent.com/4070974/189910279-aad30f39-70c0-4449-a10a-d2197a7fc7a8.png)

I would expect the email address seen in keycloak to be displayed under _email_ in the netbird instead of the _ID_ and likely the _username_ from keycloak to be displayed under _Name_ in netbird.

**Comment by braginini** [comment]
hey @finnje 
Thank you for reporting this!

This is the expected behavior so far. The Keycloak API integration is not yet there and UI uses ID instead of Email. 
NetBird doesn't store any user data, instead, it relies on the underlying IdP. The API integrations are in the [IdP package](https://github.com/netbirdio/netbird/tree/main/management/server/idp) and there is only one implementation - Auth0.

We didn't set the priority for this issue, but we'd appreciate it if someone from the community could implement the [IdP Manager interface](https://github.com/netbirdio/netbird/blob/6de313070a4e20e50e523b3e41de875e727a96f1/management/server/idp/idp.go#L11) for Keycloak using this official [Keycloak API reference](https://www.keycloak.org/docs-api/15.0/rest-api/#_users_resource)

**Comment by pnowy** [comment]
@finnje you can change it on Keycloak side. What is needed in this case is a client specific mapper which put into `sub` the email or username (email probably is better as `sub` is displayed on email column on NetBird UI).

Example config from Keycloak (Client -> Your Client (i.e. `netbird-client`)-> Client Scopes -> netbird-client-dedicated -> Add mapper -> By Configuration -> User Property):

![image](https://user-images.githubusercontent.com/3254609/201652432-020a3389-2720-431b-9b5d-8cd75cf0d212.png)

**Comment by finnje** [comment]
Nice @pnowy thanks for that!

**Comment by mlsmaycon** [comment]
@finnje we've added a better integration for keycloak with the latest versions. Please refer to: https://docs.netbird.io/selfhosted/identity-providers#step-9-add-manage-users-role-to-netbird-backend

**Comment by bravosierrasierra** [comment]
@mlsmaycon Can you add solution from https://github.com/netbirdio/netbird/issues/469#issuecomment-1313561452 to https://docs.netbird.io/selfhosted/identity-providers#keycloak ? I spend many days to find a solution for empty username from keycloak :(
