### ISSUE TITLE
Independet users working for the same comapany

### ISSUE THREAD

**Issue by kdre** [netbirdio/netbird#964]
**Describe the problem**
I work for a big company, where several working groups work independently from each other.
Recently a colleague registered to netbird with his organization email address. The plan was that I invite him afterwards to my netbird network (I registered with my private address). However, it seems that a random guy from the company also registered to netbird and my colleague could see the peers from this random guy and was stuck as a user 'under' this random guy. As a matter of fact, I could not invite my colleague to my network. Further, my colleague also didn't find a way to delete his account...

**Expected behavior**
1. If someone with the same domain is already registered, I expect that I will be asked if I want to join "his" team or if I want to create an independent account.

2. There seem not be a way to delete an account or user. Not via UI, nor via API. 

Both issues are suboptimal and I consider them as bugs...The first one seems like a security/privacy issue. The second one seems like you are collecting accounts/users and dont want to let them go... Please fix both!

**Comment by mlsmaycon** [comment]
@kdre, thanks for reporting your use case and your issue. We plan to improve our user management and add a management delete function.  In the meantime, your colleague may request an account removal by sending an email to support@netbird.io requesting removal. After that, he will need to wait for your invitation to join your account. 

Regarding the first expected behavior you described, it is a great option, and we will consider it in the next roadmap planning.
